name: Sync README to Notion

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - 'main'
    paths:
      - './README.md'

jobs:
  sync_readme_to_notion:
    runs-on: ubuntu-latest
    name: Sync README to Notion
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ensure this matches the version in action.yml

      - name: Install dependencies
        run: npm install
        
      - name: Sync README to Notion
        uses: Novia-RDI-Seafaring/notion-sync-action@v1.0.1
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_page_id: ${{ secrets.NOTION_PAGE_ID }}